language: python

python:
  - 2.7
  - 3.5
  - 3.6

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

install:
  - conda install conda-build 
  - conda config --add channels http://ssb.stsci.edu/astroconda

script: 
  - export CONDA_BLD_PATH=$HOME/conda-bld
  - conda build --py $TRAVIS_PYTHON_VERSION .

after_success:
  - conda install anaconda-client
  - conda convert --force --platform all $CONDA_BLD_PATH/linux-64/*.tar.bz2 --output-dir $CONDA_BLD_PATH
  - anaconda -t $CONDA_UPLOAD_TOKEN upload --force $CONDA_BLD_PATH/*/*.tar.bz2


