{% set name = "pandexo.engine" %}
{% set version = "master" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  git_rev: master
  git_url: https://github.com/mattjhill/PandExo.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - numpy >=1.12.1
    - bokeh ==0.12.6
    - tornado
    - pandas
    - joblib
    - pandeia.engine
    - photutils
    - astropy
    - stsci.distutils >=0.3.7
    - d2to1 >=0.2.11
    - pysynphot
    - pyfftw
    
  run:
    - python
    - numpy >=1.12.1
    - bokeh ==0.12.6
    - tornado
    - pandas
    - joblib
    - pandeia.engine
    - photutils
    - astropy
    - stsci.distutils >=0.3.7
    - d2to1 >=0.2.11
    - pysynphot
    - pyfftw

test:
  imports:
    - pandexo

about:
  description: "Getting Started\n---------------\n\nTools to help the community with planning exoplanet observations.\n\nPandExo is both an online tool and a python package for generating instrument simulations\
    \ of JWST\u2019s NIRSpec, NIRCam, NIRISS and NIRCam and HST WFC3. It uses throughput calculations from STScI\u2019s Exposure Time Calculator, Pandeia: Pandeia + Exoplanets = PandExo. This documentation\
    \ contains information on how to download, install and analyze PandExo output.\n\nShould I install PandExo or use the online interface? \n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nInstall\
    \ if... \n\n- I will be using PandExo for more than 10 runs \n- I want to submit bash runs \n- I want to use the online GUI but don't want to be subject to any slow downs because of high user frequency\
    \ \n- I want to be able to use plotting functions to analyze my output \n\nInstall EVEN if... \n\n- I am scared of Python\n\nDo not install if...\n\n- I will only be using PandExo fewer than 10 times\n\
      - I have a student who can install it for me\n\nRequires\n~~~~~~~~\n\n- Python >2.7, that's it\n\n"
  license: BSD License
  license_family: BSD
  home: The package home page
  summary: Summary of the package
  doc_url: ''
  dev_url: ''
  license_file: ''

extra:
  recipe-maintainers: ''
